#!/bin/sh /etc/rc.common
START=99
USE_PROCD=1

start_service() {
	[ "$(uci -q get bandwidth-control.main.enabled)" = 1 ] || return 0
	procd_open_instance
	procd_set_param command /bin/sh -c 'while :; do /usr/libexec/bandwidth-control/check check; sleep "$(uci -q get bandwidth-control.main.interval || echo 60)"; done'
	procd_set_param respawn 3600 5 5
	procd_close_instance
}

reload_service() { stop; start; }
